random_state: 42
debug: False

batch_size: 256
max_epochs: 5000
loss_to_monitor: 'validation/epoch_seg_loss:0'

use_vote_loss: True
use_seg_loss: True
seg_loss_weighting: 100.

gz3d_galaxies_only: False
spiral_galaxies_only: True
patience: 10
oversampling_ratio: 10

num_workers: 20
accelerator: gpu
devices: 1
precision: 16-mixed
strategy: auto

schema_name: 'desi_dr5'

# https://hydra.cc/docs/configure_hydra/workdir/
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}